In [5]:
#%%
import glob
import os

import pandas as pd
#%%
os.chdir("/Users/yenchenchou/Documents/RMDS_YC/RiskScore/RMDS_COVID19_riskgenerator")
# %%

In [9]:
df = pd.read_csv(
    "data/external/weekly_pattern/0722/patterns-part1.csv.gz", 
    compression="gzip",
    usecols=["safegraph_place_id",
             "visits_by_day",
             "visits_by_each_hour",
             "median_dwell",
             "date_range_start"])

In [10]:
df.head(3)

,safegraph_place_id,date_range_start,visits_by_day,visits_by_each_hour,median_dwell
0,sg:000a905313604e11a9dac064c6a2ae14,2020-07-13T00:00:00-05:00,"[48,49,64,45,47,80,58]","[1,0,0,0,0,0,0,1,2,0,2,5,6,5,5,2,1,1,5,3,1,5,2...",7.0
1,sg:001d6be2652d483aa132c2c17931a8a7,2020-07-13T00:00:00-05:00,"[7,17,12,12,8,5,12]","[0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,3,0,0,0...",23.0
2,sg:0053f040c11a445fab00bbb179718e4c,2020-07-13T00:00:00-05:00,"[0,1,2,1,2,1,1]","[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",6.0

In [7]:
df = pd.read_csv(
    "data/processed/RMDS_poi.csv")
df.head(5)

,safegraph_place_id,location_name,top_category,latitude,longitude,street_address,postal_code,city,open_hours_dict,community
0,sg:0125a0bd8ef24e819fb59202c8e82ef2,Carl's Jr.,Restaurants and Other Eating Places,34.660013,-118.147309,852 W Avenue L,93534,Lancaster,NaN,Lancaster
1,sg:0279d731bda448fa9e2ddc6e5b16f0fe,Brainard Elementary,Elementary and Secondary Schools,34.277411,-118.364570,11407 Brainard Ave,91342,Lake View Terrace,NaN,Sylmar
2,sg:03cc82685819430b8552eb21f39dba00,Garden Bistro,Restaurants and Other Eating Places,33.993341,-117.904565,1390 Fullerton Rd Ste 101,91748,Rowland Heights,"{ ""Mon"": [[""8:00"", ""24:00""]], ""Tue"": [[""8:00"",...",Rowland Heights
3,sg:078b14fbc06a4a438e2b5a0b0559ef47,Hair Color By Sophia Yvonne,Personal Care Services,34.039940,-118.670592,22741 Pacific Coast Hwy,90265,Malibu,NaN,Malibu
4,sg:07aafcea20184b3e9a5e9861702d0b19,Narrows Riverwalk,"Museums, Historical Sites, and Similar Institu...",34.156629,-118.291248,Narrows Riverwalk,91201,Glendale,NaN,Glendale